2/17,18情報更新
ulong32/Planisphere pull request #7
Opened 2024-02-16 13:25 UTC by ulong32

## 概要
- エジソン
- Nameless Story

の二曲のデータを追加します。

## 残タスク

- [x]  難易度データの入力
- [x] スタミナデータの入力

2024-02-17 08:42 UTC, ulong32 commented
Nameless Storyの追加日時を間違えてました。

2024-02-18 09:35 UTC, ulong32 commented
Review用画像です。
![image](https://github.com/ulong32/Planisphere/assets/64057266/621a0616-0d48-4209-b2ea-9c71fd2727f4)
![image](https://github.com/ulong32/Planisphere/assets/64057266/ea1459dd-5d0d-404c-ab90-fb5e3496c6f9)

2024-02-18 10:11 UTC, macaron924 requested changes
「Nameless Story」のOLIVIER難易度"Ⅴ"の後に余分なカンマが入っていたので修正お願いします。

2024-02-18 10:14 UTC, ulong32 commented
ce3c7e3 で修正しました。

2024-02-18 10:16 UTC, macaron924 approved these changes
LGTM

2024-02-18 10:18 UTC, merged